
spring:
  profiles:
    active: local
---
spring: 
  profiles: local 
  kafka: 
    producer: 
      bootstrap-servers: ${KAFKA_BROKER:localhost}:${KAFAK_BROKER_PORT:9092} 
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
    admin:
      properties:
        bootstrap:
          servers: ${KAFKA_BROKER:localhost}:${KAFAK_BROKER_PORT:9092}      
--- 
spring:
  profiles: dev 
  kafka: 
    producer: 
      bootstrap-servers: ${KAFKA_BROKER:localhost}:${KAFAK_BROKER_PORT:9092} 
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer   
    admin:
      properties:
        bootstrap:
          servers: ${KAFKA_BROKER:localhost}:${KAFAK_BROKER_PORT:9092} 